# Generated by Django 2.2 on 2023-06-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_details', models.CharField(max_length=30)),
                ('to', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=10)),
                ('details', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ImageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(max_length=20)),
                ('image_name', models.CharField(max_length=30)),
                ('image_location', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=300)),
                ('created_date', models.CharField(max_length=15)),
                ('created_by', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_img_id', models.CharField(max_length=10)),
                ('user_image_id', models.CharField(max_length=10)),
                ('result', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=10)),
                ('by', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=10)),
                ('image_type', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=300)),
                ('imglocation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=30)),
                ('utype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
